# Generated by Django 5.0.2 on 2024-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='link',
        ),
        migrations.AddField(
            model_name='team',
            name='fec',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='ins',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='twit',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
