# Generated by Django 5.0.2 on 2024-02-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0002_remove_team_link_team_fec_team_ins_team_twit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Tur',
        ),
    ]
