# Generated by Django 5.0.2 on 2024-02-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0003_rename_type_tur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tur',
            new_name='Type',
        ),
    ]
