# Generated by Django 5.0.2 on 2024-02-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0004_rename_tur_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='lavozim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfolder.lavozim'),
        ),
    ]
