# Generated by Django 5.0.2 on 2024-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0005_lavozim_alter_team_lavozim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('mesege', models.CharField(max_length=100)),
            ],
        ),
    ]
