# Generated by Django 5.0.2 on 2024-02-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mesege',
            new_name='messege',
        ),
    ]
